version: '3'

services:

    app:
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        image: silviotmalmeida/frontend-user-portal-app
        container_name: frontend-user-portal-app
        tty: true
        volumes:
            - ./app:/usr/frontend-user-portal
        working_dir: /usr/frontend-user-portal
        ports:
            - "3000:3000"
        networks:
            - frontend-user-portal-network
networks:
    frontend-user-portal-network:
        driver: bridge
