import './globals.css';

export const metadata = {
  title: 'Frontend do Portal do Usuário',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='scrollbar-hide'>{children}</body>
    </html>
  );
}